---
title: "Data Sanitation Justifcation"
output: github_document
---

```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
# Load used libraries
library(readr)
library(tidyverse)
library(knitr)

# Read in the merged dataset for 2011
dataset = read_csv("../../data/01_processed/2011_qx_data.csv")
```

```{r}
dataset %>% filter(qx == 0) %>% 
  ggplot(aes(x=Age, y=Country)) + geom_point() +
  geom_vline(xintercept = 30) +
  geom_vline(xintercept = 100) +
  geom_label(aes(x=36, y="BEL", label="Age=30")) +
  geom_label(aes(x=93, y="BEL", label="Age=100")) +
  ggtitle("Instances where qx=0")
```

### Instances where qx==0 for Age groups below 60

```{r}
dataset %>% filter(qx == 0) %>% 
  filter(Age < 60) %>% 
  group_by(Country) %>% 
  summarise( min(Age), max(Age),  n()  ) %>% 
  arrange(desc(`max(Age)`)) %>% 
  kable(align = 'c')
```

### Instances where qx==0 for Age groups over 60

```{r}
dataset %>% filter(qx == 0) %>% 
  filter(Age >= 60) %>% 
  group_by(Country) %>% 
  summarise( min(Age), max(Age),  n()  ) %>% 
  arrange(`min(Age)`) %>%  
  kable(align = 'c')
```
